'use client';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import type {Plan} from '../data/curriculum';
import {sources} from '../data/content';
const routes=[
 {plan:7 as Plan,id:'planes',number:'02',eyebrow:'TÉCNICOS, ESTUDIOS INCOMPLETOS Y OTRAS ÁREAS',intro:'Una vía de continuidad para quienes necesitan completar o ampliar su formación de base en economía.',profiles:[['Tienes un título técnico o de tecnólogo','Incluye titulados de carreras técnicas de menos de 8 semestres.'],['Tienes estudios universitarios incompletos','Puedes presentar tu trayectoria y las asignaturas que hayas aprobado para evaluación.'],['Tienes un título profesional de otra área','El brochure también contempla esta ruta para carreras no afines a Ingeniería Comercial.']],note:'El plan contempla hasta 7 semestres. La duración y las asignaturas a cursar dependen de las convalidaciones aprobadas por el Comité Académico.'},
 {plan:5 as Plan,id:'plan-5',number:'03',eyebrow:'PROFESIONALES CON FORMACIÓN AFÍN',intro:'Una vía para profundizar en economía a partir de una formación profesional previa relacionada con la carrera.',profiles:[['Ya tienes un título profesional','Ruta orientada a titulados de carreras de 8 semestres o más.'],['Tu formación es afín a Ingeniería Comercial','El brochure menciona Contabilidad, Administración Pública e Ingenierías, entre otras. La afinidad se evalúa individualmente.']],note:'El plan contempla hasta 5 semestres. Tener un título o haber cursado 8 semestres no asegura por sí solo esta vía: se revisan la afinidad de la formación y las asignaturas previas.'},
];
export default function AdmissionPlans({onPlan}:{onPlan:(v:Plan)=>void}){
 return <>{routes.map(route=><section id={route.id} key={route.plan} className={`admission-section admission-${route.plan} v-section`} aria-labelledby={`plan-title-${route.plan}`}><div className="v-section-line"><span>{route.number} / QUIÉNES PUEDEN POSTULAR</span><a href={route.plan===7?'#plan-5':'#planes'}>{route.plan===7?'Ver plan de 5 semestres':'Ver plan de 7 semestres'} <ArrowDown size={14}/></a></div><div className="admission-layout"><div className="admission-heading" data-rise><p className="v-eyebrow">{route.eyebrow}</p><h2 id={`plan-title-${route.plan}`}>Plan de<br/>{route.plan} semestres.</h2><p>{route.intro}</p><a className="v-link" href="#malla" onClick={()=>onPlan(route.plan)}>Ver malla de {route.plan} semestres <ArrowDown size={18}/></a></div><div className="admission-profiles" data-rise><h3>Este plan puede corresponderte si…</h3><ul>{route.profiles.map(([title,body],i)=><li key={title}><span>0{i+1}</span><div><h4>{title}</h4><p>{body}</p></div></li>)}</ul><p className="admission-note">{route.note}</p></div></div><div className="admission-next" data-rise><div><p className="v-eyebrow">ANTES DE POSTULAR</p><h3>Solicita una preconvalidación.</h3><p>Envía tu concentración de notas a admisión para una revisión previa de asignaturas. Esta consulta no constituye una postulación formal.</p></div><div className="admission-actions"><a className="v-button" href={`mailto:prosecuciones.fae@usach.cl?subject=Consulta%20de%20preconvalidaci%C3%B3n%20-%20plan%20de%20${route.plan}%20semestres`}>Consultar mi vía de ingreso <ArrowUpRight size={18}/></a><a href={`${sources.brochure}#page=9`} target="_blank" rel="noreferrer">Revisar condiciones del programa <ArrowUpRight size={15}/></a></div></div></section>)}</>;
}
