'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight} from 'lucide-react';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {curriculum,curriculumSource,area,areaColors,type Plan} from '../data/curriculum';
export default function Curriculum({plan,onPlan,reduced}:{plan:Plan;onPlan:(v:Plan)=>void;reduced:boolean}){
 const root=useRef<HTMLElement>(null),track=useRef<HTMLDivElement>(null),windowRef=useRef<HTMLDivElement>(null);const [semester,setSemester]=useState(0),[filter,setFilter]=useState('Todas');const pinned=useRef(false);
 useEffect(()=>{const trackEl=track.current,windowEl=windowRef.current,sectionEl=root.current;if(!trackEl||!windowEl||!sectionEl)return;gsap.registerPlugin(ScrollTrigger);setSemester(0);const mm=gsap.matchMedia();mm.add('(min-width: 1000px) and (min-height: 860px)',()=>{if(reduced)return;pinned.current=true;const tween=gsap.to(trackEl,{x:()=>-Math.max(0,trackEl.scrollWidth-windowEl.clientWidth+parseFloat(getComputedStyle(windowEl).paddingLeft)+parseFloat(getComputedStyle(windowEl).paddingRight)),ease:'none',scrollTrigger:{trigger:sectionEl,start:'top 96px',end:'bottom bottom',scrub:.7,invalidateOnRefresh:true,onUpdate:s=>setSemester(Math.min(plan-1,Math.round(s.progress*(plan-1))))}});return()=>{pinned.current=false;tween.kill();};});const ro=new ResizeObserver(()=>ScrollTrigger.refresh());ro.observe(sectionEl);return()=>{ro.disconnect();mm.revert();};},[plan,reduced]);
 const changePlan=(v:Plan)=>{if(v===plan)return;const anchor=window.scrollY+root.current!.getBoundingClientRect().top-96;onPlan(v);requestAnimationFrame(()=>requestAnimationFrame(()=>{windowRef.current?.scrollTo({left:0,behavior:'instant'});if(pinned.current)window.scrollTo({top:anchor,behavior:'instant'});ScrollTrigger.refresh();setSemester(0);}));};
 const jump=(i:number)=>{const next=Math.min(plan-1,Math.max(0,i));setSemester(next);if(pinned.current){const el=root.current!,top=window.scrollY+el.getBoundingClientRect().top-96,range=el.offsetHeight-innerHeight+96;window.scrollTo({top:top+range*next/(plan-1),behavior:reduced?'instant':'smooth'});}else windowRef.current?.scrollTo({left:next*296,behavior:reduced?'instant':'smooth'});};
 return <section id="malla" ref={root} className={`curriculum-section ${reduced?'curriculum-static':''}`} style={{'--semesters':plan} as React.CSSProperties}><div className="curriculum-sticky"><div className="curriculum-head"><div><p className="v-eyebrow">04 / MALLA CURRICULAR</p><h2>Tu camino,<br/><em>semestre a semestre.</em></h2></div><div className="curriculum-tools"><div className="v-segment" aria-label="Plan de la malla">{([7,5] as Plan[]).map(v=><button key={v} aria-pressed={plan===v} onClick={()=>changePlan(v)}>{v} semestres</button>)}</div><label>Explorar área<select value={filter} onChange={e=>setFilter(e.target.value)}>{['Todas',...Object.keys(areaColors)].map(v=><option key={v}>{v}</option>)}</select></label></div></div><div className="curriculum-window" ref={windowRef} onScroll={()=>{if(!pinned.current)setSemester(Math.min(plan-1,Math.round((windowRef.current?.scrollLeft||0)/296)));}}><div className="curriculum-track" ref={track}>{curriculum[plan].map((courses,i)=><article className={`semester ${semester===i?'semester-active':''}`} key={`${plan}-${i}`}><div className="semester-top"><span>{String(i+1).padStart(2,'0')}</span><div><h3>Semestre {i+1}</h3><p>Año {Math.floor(i/2)+1}</p></div></div><ul>{courses.map(course=><li key={course} className={filter!=='Todas'&&filter!==area(course)?'muted-course':''} style={{'--area-color':areaColors[area(course)]} as React.CSSProperties}><span aria-hidden="true"/><div>{course}<small>{area(course)}</small></div></li>)}</ul></article>)}</div></div><div className="curriculum-footer"><div className="semester-navigation"><button aria-label="Semestre anterior" onClick={()=>jump(semester-1)} disabled={semester===0}><ArrowLeft size={18}/></button>{curriculum[plan].map((_,i)=><button key={i} aria-label={`Ver semestre ${i+1}`} aria-current={semester===i?'step':undefined} onClick={()=>jump(i)}>{i+1}</button>)}<button aria-label="Semestre siguiente" onClick={()=>jump(semester+1)} disabled={semester===plan-1}><ArrowRight size={18}/></button></div><a href={`${curriculumSource.url}#page=${curriculumSource.pages[plan]}`} target="_blank" rel="noreferrer">Ver malla oficial <ArrowUpRight size={16}/></a></div><p className="curriculum-note">{plan===5?'El brochure identifica esta malla para profesionales de carreras afines.':'El brochure incluye técnicos, profesionales de otras áreas y estudios incompletos.'} La evaluación académica determina las asignaturas reconocidas. Las áreas de color son una agrupación de navegación.</p></div></section>;
}
